version: '3'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    #    ports:
    #  - 8090:80
    #environment:
    #  - PMA_ARBITRARY=1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080  
    environment:
     - PMA_ARBITRARY=1


  mysql:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: testdb

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWD}
    ports:
      - 6379:6379
    
